### ISSUE TITLE
Broken API of `  InboundConnectorContext#correlate(Object variables)  ` 

### ISSUE THREAD

**Issue by blondacz** [camunda/connectors#1337]
`  InboundConnectorContext#correlate(Object variables) 
`  does not return `CorrelationResult` even though the `InboundCorrelationHandler` still does. Due to this code change between 0.22 and 8.3.0 it is not possible to know whether the correlation was successful or whether the activation condition has not been met and therefore it is not possible to nack the message so it is available for processing somewhere else. 

I'd expect the Correlation result still to be used as otherwise the class does not need to be there at all.

**Comment by sbuettner** [comment]
Hey @blondacz , thanks for your request. There is currently no way whether a message was correlated successfully as its an asynchronous process in zeebe. In case of any technical error (connection/networking for example) an exception will be thrown. 

Do you require to know whether the activation condition has met? What is the use-case? Usually one can acknowledge a message after a successful `correlate` call. If the activation condition has to match to acknowledge a message there is the question why the queue should see the message in the first place as it cant process it anyway.

**Comment by blondacz** [comment]
OK. Let me change the wording.  It is impossible to know whether the correlation attempt/activation has failed. For three different errors the handler reports back the correlation result (exceptions are swallowed/converted to it).  See the `CorrelationErrorReason` and reference to it in the code. If this was surfaced then it could be handled in the connector and such message could be sent to dead letter queue or nacked for example.

**Comment by chillleader** [comment]
Hey @blondacz thanks again for raising this! As this potentially leads to lost messages, we will provide a fix ASAP.

The connector runtime will throw an exception when the correlation attempt fails for technical reasons (e.g. Zeebe unreachable).

Please note that this does **not** apply to the activation condition case mentioned above by @sbuettner. Currently there are no plans to expose `CorrelationErrorResult` via the existing `correlate` method of the SDK. When the message is not correlated because the activation condition is not met, no exception will be thrown. By default, we consider that such message can't possibly be processed and can therefore be discarded.

Is the activation condition evaluation result also important for you? (e.g. to track such messages in a DLQ like you mentioned)
If so, we will consider extending the SDK with a return type, or perhaps a configuration option to enable throwing an exception also for this case.

**Comment by blondacz** [comment]
Activation condition is important to us, as especially with more complex subscriptions (i.e. regex to multiple topics and/or more complicated filters) not all messages may meet it. You could argue that if every message on the queue + filter is supposed to activate you don't need the activation condition at all.  

So there should be a mechanism, how to communicate that the  activation condition has not been met so the message can be nacked or put on the DLQ
 
However, I don't think, that throwing the exception is the solution. 
I would consider throwing an exception in order to communicate a state/not meeting a condition, an antipattern,  as it disrupts the flow of the program.
