### ISSUE TITLE
Perform QA testing

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/connectors#53]
- [ ] write a checklist and add test cases to testrail for Connector 
- [ ] Perform QA on INT env for MS Teams Connector

Related: https://github.com/camunda/team-connectors/issues/211

Epic : https://github.com/camunda/product-hub/issues/616
Docs : https://github.com/camunda/camunda-platform-docs/blob/add_microsoft_teams_documantation/docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md

**Comment by GeethaParthasarathy** [comment]
Hey Oleksii we are going good with testing I would say we would need a min of 2 more days to test the connectors since there quite a few methods and test set up needs to be taken care of for each methods.

Meanwhile @Oleksiivanov Could you pls review the testcases in Testrail for MS teams connector
https://camunda.testrail.com/index.php?/suites/view/141&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1454

**Comment by GeethaParthasarathy** [comment]
Issues found:
https://github.com/camunda/connectors-bundle/issues/99

**Comment by GeethaParthasarathy** [comment]
@Oleksiivanov @igpetrov The latest scenario of the test run:
https://camunda.testrail.com/index.php?/runs/view/861&group_by=cases:section_id&group_id=1457&group_order=asc

**Blocked - due to lack of information /access to run the tests**

https://camunda.testrail.com/index.php?/runs/view/861&group_by=cases:section_id&group_order=asc

**New bugs found:**

https://github.com/camunda/connectors-bundle/issues/170

**Fixed bugs-Retested and passed:**

https://github.com/camunda/connectors-bundle/issues/99
https://github.com/camunda/connectors-bundle/issues/116
https://github.com/camunda/connectors-bundle/issues/117

**Comment by GeethaParthasarathy** [comment]
@Oleksiivanov  I have completed the QA for MS Teams connector and here is the status for the test run: https://camunda.testrail.com/index.php?/runs/view/861&group_by=cases:section_id&group_order=asc

Pending issues that will be handled separately:

https://github.com/camunda/connectors-bundle/issues/234
https://github.com/camunda/connectors-bundle/issues/233

**Comment by GeethaParthasarathy** [comment]
@Oleksiivanov  Pls confirm know if I can close this QA issue and the pending issues will be handled separately or I leave this issue open until everything is fixed?
