### ISSUE TITLE
Does Twilio have any security mechanism?

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/connectors#551]
Does Twilio have any security mechanism?

_Originally posted by @igpetrov in https://github.com/camunda/connectors-bundle/pull/541#discussion_r1185913014_

---

@igpetrov:

It does ([1](https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-servlet-app-by-validating-incoming-twilio-requests), [2](https://github.com/twilio/twilio-java/blob/main/src/main/java/com/twilio/security/RequestValidator.java)), and it is a little be unusual. Theoretically we can fit into our WH HMAC verification, howwever this requires some refactoring if we wish to reuse a typical inbound rest webhook connector.

Also: see https://github.com/camunda/connectors-bundle/issues/517#issuecomment-1573220998 for additional HMAC features.

**Comment by igpetrov** [comment]
As per discussion, we will investigate other webhooks https://github.com/camunda/team-connectors/issues/262. Potentially, there are two possible outcomes before we can take over the ticket:
- Implement just generic hmac verification to be as close to "industry standards" as possible, e.g. https://github.com/acquia/http-hmac-spec (hint: explore https://github.com/acquia/http-hmac-java instead of self-written one). The rest cases are abandoned, including potentially Twilio since they use query params.
- Make a configurable "HMAC toolbox" + extra configuration pieces on webhook that would allow covering bigger set of cases.
